name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [stable, unstable, development-target]
    container:
      image: ghcr.io/elementary/docker:${{ matrix.version }}

    steps:
    - uses: actions/checkout@v5
    - name: Install Dependencies
      run: |
        apt update
        apt install -y exuberant-ctags libeditorconfig-dev libgail-3-dev libgee-0.8-dev libgit2-glib-1.0-dev libgranite-dev libgtk-3-dev libgtksourceview-4-dev libgtkspell3-3-dev libhandy-1-dev libpeas-2-dev libsoup-3.0-dev libvala-dev libvte-2.91-dev meson valac polkitd libpolkit-gobject-1-dev
    - name: Build
      env:
        DESTDIR: out
      run: |
        meson build
        ninja -C build install

  flatpak:
    name: Flatpak
    runs-on: ${{ matrix.configuration.runs-on }}

    strategy:
      matrix:
        configuration:
          - arch: x86_64
            runs-on: ubuntu-latest
          - arch: aarch64
            runs-on: ubuntu-24.04-arm
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false

    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:8.2-${{ matrix.configuration.arch }}
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6.5
        with:
          bundle: code.flatpak
          manifest-path: io.elementary.code.yml
          repository-name: appcenter
          repository-url: https://flatpak.elementary.io/repo.flatpakrepo
          cache-key: "flatpak-builder-${{ github.sha }}"
          arch: ${{ matrix.configuration.arch }}

  lint:
    name: Lint
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Lint
        run: io.elementary.vala-lint -d .
